#!/bin/sh
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2017-2020 Uwe Hermann <uwe@hermann-uwe.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##

set -e

# The path where the installed sigrok libraries/binaries are located.
PREFIX=$HOME/sr_macosx

if [ "x$1" = "xsigrok-cli" ]; then
	APPNAME="sigrok-cli"
	APPNAME_BINARY="sigrok-cli"
else
	APPNAME="PulseView"
	APPNAME_BINARY="pulseview"
fi

# The path where to download files to and where to build packages.
BUILDDIR=./build_app_$APPNAME_BINARY

# We use Qt 6 for Apple Silicon support.
QTVER=qt@6

# Path to Qt5 binaries.
QTBINDIR=`brew list $QTVER | grep bin | head -n 1 | xargs dirname`
QTTRANSLATIONSDIR=`brew --prefix $QTVER`/translations

# Path to boost libraries.
BOOSTLIBDIR=`brew --prefix boost`/lib

# Path to Python 3 framework.
PYTHONFRAMEWORKDIR=`brew --prefix python@3.12`/Frameworks/Python.framework

PYVER="3.12"

# You usually don't need to change anything below this line.

# -----------------------------------------------------------------------------

# Remove build directory contents (if any) and create a new build dir.
rm -rf $BUILDDIR
mkdir $BUILDDIR
cd $BUILDDIR

APPVER="NIGHTLY"

CONTENTSDIR="$APPNAME.app/Contents"
MACOSDIR="$CONTENTSDIR/MacOS"
FRAMEWORKSDIR="$CONTENTSDIR/Frameworks"
SHARE_DIR="$CONTENTSDIR/share"
PYDIR="$FRAMEWORKSDIR/Python.framework/Versions/$PYVER"

mkdir -p $MACOSDIR $FRAMEWORKSDIR $SHARE_DIR

cp $PREFIX/bin/$APPNAME_BINARY $MACOSDIR
# Implementation detail: Shared libraries are handled below.
cp -R $PREFIX/share/libsigrokdecode $SHARE_DIR
rm -rf $SHARE_DIR/libsigrokdecode/decoders/**/__pycache__
rm -rf $SHARE_DIR/libsigrokdecode/decoders/common/**/__pycache__
cp -R $PREFIX/share/sigrok-firmware $SHARE_DIR

if [ "x$APPNAME_BINARY" = "xpulseview" ]; then
	# Manually copy some boost libs that "macdeployqt" won't copy.
	# Try with -mt suffix first, fallback to without.
	if [ -f $BOOSTLIBDIR/libboost_timer-mt.dylib ]; then
		cp $BOOSTLIBDIR/libboost_timer-mt.dylib $FRAMEWORKSDIR
		cp $BOOSTLIBDIR/libboost_chrono-mt.dylib $FRAMEWORKSDIR
	else
		cp $BOOSTLIBDIR/libboost_timer.dylib $FRAMEWORKSDIR
		cp $BOOSTLIBDIR/libboost_chrono.dylib $FRAMEWORKSDIR
	fi
	chmod 644 $FRAMEWORKSDIR/*boost*

	# Manually copy translations ("macdeployqt" won't copy them).
	mkdir -p $CONTENTSDIR/translations
	cp $QTTRANSLATIONSDIR/qt_*.qm $CONTENTSDIR/translations 2>/dev/null || true
	cp $QTTRANSLATIONSDIR/qtbase_*.qm $CONTENTSDIR/translations 2>/dev/null || true
fi

QTLIBDIR=`brew --prefix $QTVER`/lib
$QTBINDIR/macdeployqt $APPNAME.app -libpath="$QTLIBDIR"

# Copy QtDBus framework (required but not copied by macdeployqt).
if [ -d "$QTLIBDIR/QtDBus.framework" ]; then
	cp -R -L "$QTLIBDIR/QtDBus.framework" $FRAMEWORKSDIR/
fi

# Copy Python framework and fix it up.
cp -R $PYTHONFRAMEWORKDIR $FRAMEWORKSDIR
chmod 644 $PYDIR/lib/libpython*.dylib
rm -rf $PYDIR/Headers
rm -rf $PYDIR/bin
rm -rf $PYDIR/include
rm -rf $PYDIR/share
rm -rf $PYDIR/lib/pkgconfig
rm -rf $PYDIR/lib/python$PYVER/lib2to3
rm -rf $PYDIR/lib/python$PYVER/distutils
rm -rf $PYDIR/lib/python$PYVER/idlelib
rm -rf $PYDIR/lib/python$PYVER/test
rm -rf $PYDIR/lib/python$PYVER/**/test
rm -rf $PYDIR/lib/python$PYVER/tkinter
rm -rf $PYDIR/lib/python$PYVER/turtledemo
rm -rf $PYDIR/lib/python$PYVER/unittest
rm -rf $PYDIR/lib/python$PYVER/__pycache__
rm -rf $PYDIR/lib/python$PYVER/**/__pycache__
rm -rf $PYDIR/lib/python$PYVER/**/**/__pycache__
rm -rf $PYDIR/Resources
install_name_tool -change \
	/usr/local/opt/python/Frameworks/Python.framework/Versions/$PYVER/Python \
	@executable_path/../Frameworks/Python.framework/Versions/$PYVER/Python \
	$FRAMEWORKSDIR/libsigrokdecode.*.dylib
install_name_tool -change \
	/usr/local/opt/python/Frameworks/Python.framework/Versions/$PYVER/Python \
	@executable_path/../Frameworks/Python.framework/Versions/$PYVER/Python \
	$PREFIX/lib/libirmp.*.dylib

# Add wrapper (sets PYTHONHOME/SIGROK_FIRMWARE_DIR/SIGROKDECODE_DIR).
mv $MACOSDIR/$APPNAME_BINARY $MACOSDIR/$APPNAME_BINARY.real
cat > $MACOSDIR/$APPNAME_BINARY << EOF
#!/bin/sh
DIR="\$(dirname "\$0")"
cd "\$DIR"
export DYLD_LIBRARY_PATH="../Frameworks"
export PYTHONHOME="../Frameworks/Python.framework/Versions/$PYVER"
export SIGROK_FIRMWARE_DIR="../share/sigrok-firmware"
export SIGROKDECODE_DIR="../share/libsigrokdecode/decoders"
exec ./$APPNAME_BINARY.real "\$@"
EOF
chmod 755 $MACOSDIR/$APPNAME_BINARY

cp ../contrib/Info.plist_$APPNAME_BINARY $CONTENTSDIR/Info.plist
cp ../contrib/$APPNAME_BINARY.icns $CONTENTSDIR/Resources

# Code sign for Apple Silicon compatibility.
find $FRAMEWORKSDIR/Python.framework -type f \( -name "*.dylib" -o -name "*.so" -o -name "Python" \) -exec codesign --force --sign - {} \; 2>/dev/null || true
find $FRAMEWORKSDIR -name "*.dylib" -exec codesign --force --sign - {} \; 2>/dev/null || true
find $FRAMEWORKSDIR -name "*.framework" -exec codesign --force --sign - {} \; 2>/dev/null || true
codesign --force --sign - $MACOSDIR/$APPNAME_BINARY.real 2>/dev/null || true
codesign --force --sign - $APPNAME.app 2>/dev/null || true

hdiutil create "${APPNAME}-${APPVER}.dmg" -volname "$APPNAME $APPVER" \
	-fs HFS+ -srcfolder "$APPNAME.app"
