#!/bin/sh
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2017-2020 Uwe Hermann <uwe@hermann-uwe.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##

set -e

# The path where the installed sigrok libraries/binaries are located.
PREFIX=$HOME/sr_macosx

if [ "x$1" = "xsigrok-cli" ]; then
	APPNAME="sigrok-cli"
	APPNAME_BINARY="sigrok-cli"
else
	APPNAME="PulseView"
	APPNAME_BINARY="pulseview"
fi

# The path where to download files to and where to build packages.
BUILDDIR=./build_app_$APPNAME_BINARY

# We use Qt 6 for Apple Silicon compatibility and modern macOS support.
QTVER=qt@6

# Path to Qt5 binaries.
QTBINDIR=`brew list $QTVER | grep bin | head -n 1 | xargs dirname`
QTTRANSLATIONSDIR=`brew --prefix $QTVER`/translations

# Path to boost libraries.
BOOSTLIBDIR=`brew --prefix boost`/lib

# Detect Python 3 version dynamically
PYVER=$(python3 --version 2>&1 | grep -oE '[0-9]+\.[0-9]+' | head -1)
if [ -z "$PYVER" ]; then
	echo "ERROR: Could not detect Python 3 version"
	exit 1
fi
echo "Auto-detected Python version: $PYVER"

# Detect Python 3 Homebrew formula
PYTHON_FORMULA=$(brew list --formula 2>/dev/null | grep -E '^python@3\.[0-9]+$' | head -1)
if [ -z "$PYTHON_FORMULA" ]; then
	PYTHON_FORMULA="python3"
fi

# Path to Python 3 framework - try multiple locations
PYTHON_PREFIX=`brew --prefix $PYTHON_FORMULA 2>/dev/null`
if [ -d "$PYTHON_PREFIX/Frameworks/Python.framework" ]; then
	PYTHONFRAMEWORKDIR="$PYTHON_PREFIX/Frameworks/Python.framework"
elif [ -d "/Library/Frameworks/Python.framework" ]; then
	PYTHONFRAMEWORKDIR="/Library/Frameworks/Python.framework"
else
	echo "ERROR: Could not find Python.framework"
	echo "Tried: $PYTHON_PREFIX/Frameworks/Python.framework"
	echo "Tried: /Library/Frameworks/Python.framework"
	exit 1
fi

# You usually don't need to change anything below this line.

# -----------------------------------------------------------------------------

echo "=== DMG Build Configuration ==="
echo "Qt version: $QTVER"
echo "Qt bin dir: $QTBINDIR"
echo "Python version: $PYVER"
echo "Python framework: $PYTHONFRAMEWORKDIR"
echo "Boost lib dir: $BOOSTLIBDIR"
echo "==============================="
echo ""

# Remove build directory contents (if any) and create a new build dir.
rm -rf $BUILDDIR
mkdir $BUILDDIR
cd $BUILDDIR

APPVER="NIGHTLY"

CONTENTSDIR="$APPNAME.app/Contents"
MACOSDIR="$CONTENTSDIR/MacOS"
FRAMEWORKSDIR="$CONTENTSDIR/Frameworks"
SHARE_DIR="$CONTENTSDIR/share"
PYDIR="$FRAMEWORKSDIR/Python.framework/Versions/$PYVER"

mkdir -p $MACOSDIR $FRAMEWORKSDIR $SHARE_DIR

cp $PREFIX/bin/$APPNAME_BINARY $MACOSDIR
# Implementation detail: Shared libraries are handled below.
cp -R $PREFIX/share/libsigrokdecode $SHARE_DIR
rm -rf $SHARE_DIR/libsigrokdecode/decoders/**/__pycache__
rm -rf $SHARE_DIR/libsigrokdecode/decoders/common/**/__pycache__
cp -R $PREFIX/share/sigrok-firmware $SHARE_DIR

if [ "x$APPNAME_BINARY" = "xpulseview" ]; then
	# Manually copy some boost libs that "macdeployqt" won't copy.
	# Try with -mt suffix first (older Homebrew), then without (newer Homebrew)
	if [ -f $BOOSTLIBDIR/libboost_timer-mt.dylib ]; then
		cp $BOOSTLIBDIR/libboost_timer-mt.dylib $FRAMEWORKSDIR
		cp $BOOSTLIBDIR/libboost_chrono-mt.dylib $FRAMEWORKSDIR
	else
		cp $BOOSTLIBDIR/libboost_timer.dylib $FRAMEWORKSDIR
		cp $BOOSTLIBDIR/libboost_chrono.dylib $FRAMEWORKSDIR
	fi
	chmod 644 $FRAMEWORKSDIR/*boost*

	# Manually copy translations ("macdeployqt" won't copy them).
	mkdir -p $CONTENTSDIR/translations
	cp $QTTRANSLATIONSDIR/qt_*.qm $CONTENTSDIR/translations 2>/dev/null || true
	cp $QTTRANSLATIONSDIR/qtbase_*.qm $CONTENTSDIR/translations 2>/dev/null || true
fi

# Set library path for macdeployqt to find Qt frameworks
QTLIBDIR=`brew --prefix $QTVER`/lib
echo "Qt lib dir: $QTLIBDIR"
echo "Running macdeployqt..."
$QTBINDIR/macdeployqt $APPNAME.app -verbose=2 -libpath="$QTLIBDIR"

# Copy Python framework and fix it up.
cp -R $PYTHONFRAMEWORKDIR $FRAMEWORKSDIR
chmod 644 $PYDIR/lib/libpython*.dylib
rm -rf $PYDIR/Headers
rm -rf $PYDIR/bin
rm -rf $PYDIR/include
rm -rf $PYDIR/share
rm -rf $PYDIR/lib/pkgconfig
rm -rf $PYDIR/lib/python$PYVER/lib2to3
rm -rf $PYDIR/lib/python$PYVER/distutils
rm -rf $PYDIR/lib/python$PYVER/idlelib
rm -rf $PYDIR/lib/python$PYVER/test
rm -rf $PYDIR/lib/python$PYVER/**/test
rm -rf $PYDIR/lib/python$PYVER/tkinter
rm -rf $PYDIR/lib/python$PYVER/turtledemo
rm -rf $PYDIR/lib/python$PYVER/unittest
rm -rf $PYDIR/lib/python$PYVER/__pycache__
rm -rf $PYDIR/lib/python$PYVER/**/__pycache__
rm -rf $PYDIR/lib/python$PYVER/**/**/__pycache__
rm -rf $PYDIR/Resources

# Fix Python framework references in libraries
# Detect the actual Python framework path used during build
PYTHON_FRAMEWORK_BUILD_PATH="$PYTHON_PREFIX/Frameworks/Python.framework/Versions/$PYVER/Python"
if [ ! -f "$PYTHON_FRAMEWORK_BUILD_PATH" ]; then
	# Try alternate location
	PYTHON_FRAMEWORK_BUILD_PATH="/Library/Frameworks/Python.framework/Versions/$PYVER/Python"
fi

echo "Fixing Python framework references..."
for lib in $FRAMEWORKSDIR/libsigrokdecode.*.dylib $PREFIX/lib/libirmp.*.dylib; do
	if [ -f "$lib" ]; then
		install_name_tool -change \
			"$PYTHON_FRAMEWORK_BUILD_PATH" \
			@executable_path/../Frameworks/Python.framework/Versions/$PYVER/Python \
			"$lib" 2>/dev/null || true
		# Also try the old hardcoded path for compatibility
		install_name_tool -change \
			/usr/local/opt/python/Frameworks/Python.framework/Versions/$PYVER/Python \
			@executable_path/../Frameworks/Python.framework/Versions/$PYVER/Python \
			"$lib" 2>/dev/null || true
	fi
done

# Add wrapper (sets PYTHONHOME/SIGROK_FIRMWARE_DIR/SIGROKDECODE_DIR).
mv $MACOSDIR/$APPNAME_BINARY $MACOSDIR/$APPNAME_BINARY.real
# Create wrapper script dynamically with detected Python version
cat > $MACOSDIR/$APPNAME_BINARY << EOF
#!/bin/sh
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2017-2020 Uwe Hermann <uwe@hermann-uwe.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##

DIR="\$(dirname "\$0")"
cd "\$DIR"
export DYLD_LIBRARY_PATH="../Frameworks"
export PYTHONHOME="../Frameworks/Python.framework/Versions/$PYVER"
export SIGROK_FIRMWARE_DIR="../share/sigrok-firmware"
export SIGROKDECODE_DIR="../share/libsigrokdecode/decoders"
exec ./$APPNAME_BINARY.real "\$@"
EOF
chmod 755 $MACOSDIR/$APPNAME_BINARY

cp ../contrib/Info.plist_$APPNAME_BINARY $CONTENTSDIR/Info.plist
cp ../contrib/$APPNAME_BINARY.icns $CONTENTSDIR/Resources

# Code sign the application bundle (required for Apple Silicon)
echo "Code signing the application..."
# Sign Python framework separately first (if it exists)
if [ -d "$FRAMEWORKSDIR/Python.framework" ]; then
	echo "Signing Python framework..."
	# Remove signature-related extended attributes that might cause issues
	xattr -cr "$FRAMEWORKSDIR/Python.framework" 2>/dev/null || true
	# Sign the actual Python library
	codesign --force --sign - "$PYDIR/Python" 2>/dev/null || true
	codesign --force --sign - "$PYDIR/lib/libpython"*.dylib 2>/dev/null || true
fi
# Sign all other frameworks and libraries
find "$FRAMEWORKSDIR" -name "*.dylib" -type f -exec codesign --force --sign - {} \; 2>/dev/null || true
find "$FRAMEWORKSDIR" -name "*.framework" -type d -depth 1 ! -name "Python.framework" -exec codesign --force --sign - {} \; 2>/dev/null || true
# Sign plugins
find "$CONTENTSDIR/PlugIns" -name "*.dylib" -type f -exec codesign --force --sign - {} \; 2>/dev/null || true
# Finally sign the main app bundle
codesign --force --sign - "$MACOSDIR/$APPNAME_BINARY.real"
codesign --force --sign - $APPNAME.app
echo "Verifying code signature..."
codesign --verify --verbose $APPNAME.app || echo "Warning: Signature verification failed but continuing..."

hdiutil create "${APPNAME}-${APPVER}.dmg" -volname "$APPNAME $APPVER" \
	-fs HFS+ -srcfolder "$APPNAME.app"
