#!/bin/sh
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2015 Uwe Hermann <uwe@hermann-uwe.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##

set -e

# The path where the compiled packages will be installed.
PREFIX=$HOME/sr_macosx

# The path where to download files to and where to build packages.
BUILDDIR=./build

# Detect Python 3 version dynamically
PYTHON3_VERSION=$(python3 --version 2>&1 | grep -oE '[0-9]+\.[0-9]+' | head -1)
if [ -z "$PYTHON3_VERSION" ]; then
	echo "ERROR: Could not detect Python 3 version"
	exit 1
fi
echo "Detected Python version: $PYTHON3_VERSION"

# The path where the libsigrok Python bindings will be installed.
PYPATH=$PREFIX/lib/python${PYTHON3_VERSION}/site-packages

# Edit this to control verbose build output.
# V="V=1 VERBOSE=1"

# Edit this to enable/disable/modify parallel compiles.
PARALLEL="-j "`sysctl -n hw.ncpu`

# Uncomment the following lines to build with clang and run scan-build.
# export CC=llvm-gcc
# export CXX=llvm-g++
# SB="scan-build -k -v"

# Uncomment the following lines to build with gcc/g++.
export CC=gcc
export CXX=g++

# Detect architecture for Apple Silicon support
ARCH=$(uname -m)
if [ "$ARCH" = "arm64" ]; then
	# Native Apple Silicon build
	CMAKE_OSX_ARCH="arm64"
else
	# Intel build (can also build universal binaries if needed)
	CMAKE_OSX_ARCH="x86_64"
fi

# Uncomment the following line to build universal binaries (both Intel and Apple Silicon)
# CMAKE_OSX_ARCH="arm64;x86_64"

# We use Qt 6 for Apple Silicon compatibility and modern macOS support.
QTVER=qt@6

# Path to Qt5 binaries (needed for cmake to find the Qt5 libs).
export PATH="$(brew --prefix $QTVER)/bin:$PATH"

# You usually don't need to change anything below this line.

# -----------------------------------------------------------------------------

# PKG_CONFIG_PATH will need to point to pkg-config files of Homebrew's
# keg-only formulae.
P="$PREFIX/lib/pkgconfig"
# Detect Python 3 Homebrew formula (python@3.x)
PYTHON_FORMULA=$(brew list --formula 2>/dev/null | grep -E '^python@3\.[0-9]+$' | head -1)
if [ -z "$PYTHON_FORMULA" ]; then
	# Fallback to generic python3
	PYTHON_FORMULA="python3"
fi
echo "Using Homebrew Python formula: $PYTHON_FORMULA"
for FORMULA in libffi "$PYTHON_FORMULA" "$QTVER"; do
    P="$P:$(brew --prefix "$FORMULA")/lib/pkgconfig"
done

# Extra options to pass to configure.
C="$C --prefix=$PREFIX"

# Remove build directory contents (if any) and create a new build dir.
rm -rf $BUILDDIR
mkdir $BUILDDIR
cd $BUILDDIR

GIT_CLONE="git clone --depth=1"

REPO_BASE="git://sigrok.org"

# -----------------------------------------------------------------------------

# libserialport
$GIT_CLONE $REPO_BASE/libserialport
cd libserialport
./autogen.sh
mkdir build
cd build
../configure $C
$SB make $PARALLEL $V
make install $V
cd ../..

# libsigrok
mkdir -p $PYPATH
$GIT_CLONE $REPO_BASE/libsigrok
cd libsigrok
./autogen.sh
mkdir build
cd build
PKG_CONFIG_PATH=$P ../configure $C
$SB make $PARALLEL $V
PYTHONPATH=$PYPATH $SB make install $V
$SB make check $V
cd ../..

# libsigrokdecode
$GIT_CLONE $REPO_BASE/libsigrokdecode
cd libsigrokdecode
./autogen.sh
mkdir build
cd build
PKG_CONFIG_PATH=$P ../configure $C PYTHON3=python3
$SB make $PARALLEL $V
make install $V
$SB make check $V
cd ../..

# sigrok-firmware
$GIT_CLONE $REPO_BASE/sigrok-firmware
cd sigrok-firmware
./autogen.sh
mkdir build
cd build
# Nothing gets cross-compiled here, we just need 'make install' basically.
../configure $C
make install $V
cd ../..

# sigrok-firmware-fx2lafw
$GIT_CLONE $REPO_BASE/sigrok-firmware-fx2lafw
cd sigrok-firmware-fx2lafw
./autogen.sh
mkdir build
cd build
# We're building the fx2lafw firmware on the host, no need to cross-compile.
../configure $C
make $PARALLEL $V
make install $V
cd ../..

# sigrok-cli
$GIT_CLONE $REPO_BASE/sigrok-cli
cd sigrok-cli
./autogen.sh
mkdir build
cd build
PKG_CONFIG_PATH=$P ../configure $C
$SB make $PARALLEL $V
make install $V
cd ../..

# PulseView
$GIT_CLONE $REPO_BASE/pulseview
cd pulseview
mkdir build
cd build
PKG_CONFIG_PATH=$P $SB cmake -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -DCMAKE_OSX_ARCHITECTURES="$CMAKE_OSX_ARCH" -DDISABLE_WERROR=y -DENABLE_TESTS=y ..
$SB make $PARALLEL $V
make install $V
$SB make test $V
cd ../..

